### ISSUE TITLE
Code testing

### ISSUE THREAD

**Issue by gregoryross** [choderalab/software-development#15]
@gregoryross (with help from @bas-rustenburg) to address:
- the benefits of test driven coding
- how to write informative tests, including
  -  the format of the tests (e.g. `tests/test_function.py`)
  - the testing logic (e.g. don't test more than output at a time)
- the software used to test (e.g. `pytests`, `nose`)
- how to automate testing

**Comment by jchodera** [comment]
@marscher points out that `nosetests` is no longer being maintain, and [`pytest`](http://doc.pytest.org) is a more modern framework.

**Comment by bas-rustenburg** [comment]
While `nosetests` support will end, don't forget nose2: http://nose2.readthedocs.io/en/latest/

**Comment by bas-rustenburg** [comment]
I came across this website, looks really helpful. http://pythontesting.net/start-here/

**Comment by gregoryross** [comment]
Here's another good site:
http://docs.python-guide.org/en/latest/writing/tests/

**Comment by gregoryross** [comment]
It would also be helpful to setting on a particular testing framework for the lab. I personally like `pytest`.

**Comment by bas-rustenburg** [comment]
This is probably my favorite guide on python tests:

http://docs.python-guide.org/en/latest/writing/tests/

**Comment by jchodera** [comment]
Drafted in #27
