### ISSUE TITLE
How to: documentation 

### ISSUE THREAD

**Issue by bas-rustenburg** [choderalab/software-development#16]
How to write documentation for scientific software. Discuss tools like read the docs, sphinx, et cetera.

**Comment by jchodera** [comment]
* Sphinx / RTD examples: [protons](http://constph-openmm.readthedocs.io) | [ensembler](http://ensembler.readthedocs.io)
* Sphinx / S3 examples: [mdtraj](http://mdtraj.org/) | [pymbar](http://pymbar.org/) | [yank](http://getyank.org)
* Collaborative documentation writing: [readme.io](http://readme.io)

Sphinx material:
* @bas-rustenburg's tutorial on [setting up sphinx documentation](https://github.com/choderalab/Protons/blob/master/howto-documentation.rst)
* [Sphinx tutorial](http://www.sphinx-doc.org/en/stable/tutorial.html)

**Comment by jchodera** [comment]
[autoprotocol](http://autoprotocol.org) has a great example of good [changelog documentation](http://autoprotocol-python.readthedocs.io/en/latest/changelog.html).

**Comment by bas-rustenburg** [comment]
Thoughts and links on this topic in a nutshell:

- Documentation is the primary way to learn about how code works.
- Clear examples encourage use of code.

There are many tools that can be used to write documentation. The easiest to start with is [Github wiki](https://help.github.com/articles/about-github-wikis/) which uses markdown syntax just like the rest of github. 

If you need something slightly more powerful, consider using [sphinx](http://www.sphinx-doc.org/en/stable/tutorial.html). 
Hosting a sphinx project can be tricky on its own, but is almost trivial if you have a public repository, since you can use [readthedocs](https://docs.readthedocs.io/en/latest/getting_started.html).

If you're using conda for your code, you may want to check out a step to step guide on setting up a conda project with read the docs, [here](https://github.com/choderalab/Protons/blob/master/howto-documentation.rst).

**Comment by bas-rustenburg** [comment]
https://guides.github.com/features/wikis/   Helpful guide on Github wikis .

**Comment by bas-rustenburg** [comment]
A tempate for sphinx/read the docs 
https://github.com/readthedocs/template

**Comment by bas-rustenburg** [comment]
wiki example:
https://github.com/d3/d3/wiki

Sphinx examples:
https://github.com/choderalab/yank/tree/master/docs
https://github.com/pymc-devs/pymc/tree/master/docs

**Comment by jchodera** [comment]
Addressed in #28
