### ISSUE TITLE
Docstring format recommendations

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/software-development#2]
I think it would be helpful to encourage:
- Everyone to write informative docstrings
- Additionally, to write docstrings that can be compiled into useful pages such as with sphinx. For this, there are several format options, such as numpy style and restructured text. 

Although I have personally favored the numpy style in the past, I actually think the numpy standard is harder to comply with, so it might be easier to generate docs with restructured text.

**Comment by bas-rustenburg** [comment]
I think we could view this as either part of documentation, or code style.

**Comment by andrrizzi** [comment]
Happy to help out.

**Comment by andrrizzi** [comment]
I wrote about this in #23 . I'll include a link to the how-to documentation article described by #16 when it'll be in. Feel free to reopen if you think the point needs to be expanded on that article!
