### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by jchodera** [choderalab/software-development#3]
We should cover continuous integration for testing of software and packaging.

We currently use
- [travis-ci](https://travis-ci.com/) for `linux` and `osx`
- [appveyor](https://www.appveyor.com/) for `win`

We also use https://nightli.es/ for triggering nightly builds to make sure code doesn't go stale due to changes in upstream dependencies.

We try to make this easier by using a `devtools/` boilerplate:
https://github.com/omnia-md/devtools

**Comment by Lnaden** [comment]
- Setting up Travis
- Setting up appveyor
- Setting configuring all the ci
- What to test
- What is different between a CI environment and what the user will install/use

@jchodera We'll need the docs you already have on configuring travis and appveyor

Are there other CI platforms we recommend?

**Comment by jchodera** [comment]
@marscher has been exploring [CircleCI](https://circleci.com/) as an alternative to travis, with some interesting [features](https://circleci.com/features/).

**Comment by Lnaden** [comment]
Interesting, I'll see if there is anything in there to bring into the writeup

**Comment by jchodera** [comment]
I think the support for [retrieving build artifacts](https://circleci.com/docs/build-artifacts/) could be useful.
