### ISSUE TITLE
Broken link in Philosophy and Scope

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/software-development#36]
There's a link to "software entropy" in the [Philosophy and Scope page](https://github.com/choderalab/software-development/blob/master/PHILOSOPHY_AND_SCOPE.md) that seems to be broken. I'm not sure where it should point to, otherwise I'd fix it myself.

**Comment by jchodera** [comment]
Good catch! Should be https://en.m.wikipedia.org/wiki/Software_entropy

**Comment by pgrinaway** [comment]
Addressing in #37
