### ISSUE TITLE
Create a boilerplate package these docs can reference

### ISSUE THREAD

**Issue by Lnaden** [choderalab/software-development#54]
It would be helpful to have a boilerplate package that these docs can reference as an example. As discussed in #53.

The question is do we want to have it as part of this repository, or as its own repository?

If we have it as part of this repository:
* We can update the example in the same PR's and commits as the documentations
* It would increase the size and complexity of this repository, possibly reducing approachability.

If we have it separate:
* This repository stays clean and small
* There is a separate repo which has to be updated asynchronously with this repository.

**Comment by Lnaden** [comment]
One suggestion from @ctk3b in #53 is to make "a compchem focused [cookiecutter](https://github.com/audreyr/cookiecutter) repo."

**Comment by davidlmobley** [comment]
You guys could also do an article for Livecoms on this stuff and have an associated github repo. I've pitched this idea to Beckstein too and he had some interest, so maybe a team effort with him?  A great way to get academic credit for doing it and disseminate more broadly, perhaps.
