### ISSUE TITLE
Cookiecutter for Computational Chemistry Python Packages

### ISSUE THREAD

**Issue by Lnaden** [choderalab/software-development#57]
I have created a [Cookiecutter](https://github.com/audreyr/cookiecutter) following the guidelines in this instructional that I would like to ask people to look over and comment on:

[Cookiecutter for Computational Chemistry Python Packages]https://github.com/choderalab/cookiecutter-python-comp-chem

People should be able to build their new packages from that template to create a skeletal structure, basic `setup.py`, CI testing (fix for #22), unit tests, documents, and GitHub hooks. This should also be a full fix for #54. 

Feedback is welcome there and here!

cc @dgasmith @ctk3b

**Comment by Lnaden** [comment]
We should link the cookiecutter once it has some cleanup and maybe a better home.

**Comment by davidlmobley** [comment]
cc @bannanc

**Comment by jchodera** [comment]
This was addressed by #58.
