### ISSUE TITLE
Python code formatter

### ISSUE THREAD

**Issue by malramsay64** [choderalab/software-development#62]
There is a section in Python Coding about formatting to [pep8](https://github.com/choderalab/software-development/blob/master/PYTHON_CODING.md#keep-clean-and-adhere-to-pep8) style. As an alternative to manually formatting the code and having to know pep8 there are some automatic code formatting tools notably [yapf](https://github.com/google/yapf) and [black](https://github.com/ambv/black). These tools could be worth mentioning.

**Comment by chfw** [comment]
Please close this issue as my PR has done it.

**Comment by chfw** [comment]
https://github.com/choderalab/software-development/pull/77

**Comment by jchodera** [comment]
Closed by #77
